obj-$(CONFIG_AXI_ADXCVR) += axi_adxcvr.o axi_adxcvr_eyescan.o
obj-$(CONFIG_AXI_JESD204_RX) += axi_jesd204_rx.o
obj-$(CONFIG_AXI_JESD204_TX) += axi_jesd204_tx.o
obj-$(CONFIG_XILINX_TRANSCEIVER) += xilinx_transceiver.o
